#!/usr/bin/env python3
"""Regenerates OptionPricing/UI/LightweightChartsJs.inc from the vendored library.

Usage: python3 Tools/embed_chart_bundle.py
"""
import pathlib

root = pathlib.Path(__file__).resolve().parents[1]
source = root / "ThirdParty" / "lightweight-charts" / "lightweight-charts.standalone.production.js"
target = root / "OptionPricing" / "UI" / "LightweightChartsJs.inc"

js = source.read_text(encoding="utf-8")
delimiter = "LWC_EMBED"
assert f"){delimiter}\"" not in js, "raw string delimiter collides with the library source"

# Split into chunks: a single raw string literal of this size is fine for clang, but
# keeping chunks under 60 KB stays well clear of any compiler literal limits.
chunk = 60000
parts = [js[i:i + chunk] for i in range(0, len(js), chunk)]
body = "\n".join(f'    R"{delimiter}({p}){delimiter}"' for p in parts)

target.write_text(
    "// GENERATED by Tools/embed_chart_bundle.py from ThirdParty/lightweight-charts.\n"
    "// TradingView Lightweight Charts(TM) v4.2.3, Apache License 2.0. Do not edit by hand.\n"
    "// Included by LightweightChartsJs.cpp.\n"
    "const char* const kLightweightChartsJs =\n" + body + ";\n",
    encoding="utf-8",
)
print(f"wrote {target} ({len(js)} bytes in {len(parts)} chunks)")
